import PDFDocument from 'pdfkit'

const COLORS = {
  ink:    '#0D0D0D',
  accent: '#1A4D3C',
  muted:  '#6B6B6B',
  border: '#E2E0D8',
  pass:   '#1A4D3C',
  fail:   '#C84B31',
  warn:   '#C87A1A',
  bg:     '#F7F6F2',
  white:  '#FFFFFF',
}

const FRAMEWORK_LABELS = {
  soc2:     'SOC 2 Type II',
  iso27001: 'ISO 27001',
  gdpr:     'GDPR',
  hipaa:    'HIPAA',
  pci_dss:  'PCI-DSS',
}

/**
 * Generates a professional compliance evidence PDF.
 * Returns a Buffer.
 */
export async function generateEvidencePdf({ org, framework, controls, scans, score, generatedAt, generatedBy }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 60, bottom: 60, left: 60, right: 60 },
      info: {
        Title: `${FRAMEWORK_LABELS[framework] || framework} Evidence Pack — ${org.name}`,
        Author: 'iFu Labs Comply',
        Subject: 'Compliance Evidence Report',
        Creator: 'iFu Labs — Comply'
      }
    })

    const chunks = []
    doc.on('data', chunk => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    // ── Cover Page ─────────────────────────────────────────────────────────
    coverPage(doc, { org, framework, score, generatedAt, generatedBy })

    // ── Table of Contents ──────────────────────────────────────────────────
    doc.addPage()
    tableOfContents(doc, controls)

    // ── Executive Summary ──────────────────────────────────────────────────
    doc.addPage()
    executiveSummary(doc, { org, framework, controls, scans, score, generatedAt })

    // ── Controls by Category ───────────────────────────────────────────────
    const categories = [...new Set(controls.map(c => c.category))]
    for (const category of categories) {
      const categoryControls = controls.filter(c => c.category === category)
      doc.addPage()
      controlSection(doc, category, categoryControls)
    }

    // ── Scan History ───────────────────────────────────────────────────────
    if (scans.length > 0) {
      doc.addPage()
      scanHistory(doc, scans)
    }

    // ── Footer on every page ───────────────────────────────────────────────
    const range = doc.bufferedPageRange()
    const pageCount = range.count
    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(range.start + i)
      pageFooter(doc, i + 1, pageCount, org.name)
    }

    doc.end()
  })
}

// ── Page builders ──────────────────────────────────────────────────────────

function coverPage(doc, { org, framework, score, generatedAt, generatedBy }) {
  const { width, height } = doc.page

  // Dark header band
  doc.rect(0, 0, width, 220).fill(COLORS.accent)

  // Logo mark
  doc.save()
  doc.translate(60, 60)
  doc.polygon([16, 0], [32, 9], [32, 27], [16, 36], [0, 27], [0, 9])
    .stroke(COLORS.white).lineWidth(1.5)
  doc.polygon([16, 12], [24, 17], [24, 27], [16, 32], [8, 27], [8, 17])
    .fill(COLORS.white)
  doc.restore()

  // iFu Labs Comply wordmark
  doc.fillColor(COLORS.white)
    .font('Helvetica')
    .fontSize(14)
    .text('iFu Labs Comply', 100, 72)

  // Report title
  doc.fillColor(COLORS.white)
    .font('Helvetica-Bold')
    .fontSize(28)
    .text(`${FRAMEWORK_LABELS[framework] || framework}`, 60, 120)

  doc.fillColor('rgba(255,255,255,0.7)')
    .font('Helvetica')
    .fontSize(16)
    .text('Evidence & Audit Pack', 60, 156)

  // Score circle
  const cx = width - 110, cy = 130, r = 50
  doc.circle(cx, cy, r).fill('rgba(255,255,255,0.15)')
  doc.fillColor(COLORS.white)
    .font('Helvetica-Bold')
    .fontSize(32)
    .text(`${score}%`, cx - 30, cy - 22, { width: 60, align: 'center' })
  doc.fillColor('rgba(255,255,255,0.7)')
    .font('Helvetica')
    .fontSize(10)
    .text('Overall Score', cx - 30, cy + 14, { width: 60, align: 'center' })

  // Meta block
  const metaY = 260
  doc.fillColor(COLORS.ink).font('Helvetica-Bold').fontSize(20)
    .text(org.name, 60, metaY)

  const metaItems = [
    ['Organization', org.name],
    ['Framework', FRAMEWORK_LABELS[framework] || framework],
    ['Generated', generatedAt.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })],
    ['Prepared by', generatedBy?.email || 'iFu Labs Comply'],
    ['Report type', 'Automated Evidence Collection'],
  ]

  let y = metaY + 40
  for (const [label, value] of metaItems) {
    doc.fillColor(COLORS.muted).font('Helvetica').fontSize(9)
      .text(label.toUpperCase(), 60, y)
    doc.fillColor(COLORS.ink).font('Helvetica').fontSize(11)
      .text(value, 60, y + 12)
    y += 36
  }

  // Disclaimer box
  doc.rect(60, doc.page.height - 140, doc.page.width - 120, 70)
    .fill(COLORS.bg)
  doc.fillColor(COLORS.muted).font('Helvetica').fontSize(8)
    .text(
      'This report was automatically generated by iFu Labs Comply. It is intended for use in compliance reviews and audit preparation. Control evidence is collected via read-only API access and reflects the state of your environment at the time of each scan.',
      68, doc.page.height - 132, { width: doc.page.width - 136 }
    )
}

function tableOfContents(doc, controls) {
  sectionHeader(doc, 'Table of Contents')

  const categories = [...new Set(controls.map(c => c.category))]
  const items = [
    'Executive Summary',
    ...categories,
    'Scan History',
  ]

  let y = doc.y + 20
  items.forEach((item, i) => {
    doc.fillColor(COLORS.ink).font('Helvetica').fontSize(11)
      .text(`${i + 1}.  ${item}`, 60, y)
    y += 24
  })
}

function executiveSummary(doc, { org, framework, controls, scans, score, generatedAt }) {
  sectionHeader(doc, 'Executive Summary')

  const passing  = controls.filter(c => c.status === 'pass').length
  const failing  = controls.filter(c => c.status === 'fail').length
  const review   = controls.filter(c => c.status === 'review').length
  const pending  = controls.filter(c => c.status === 'pending' || !c.status).length
  const total    = controls.length
  const critical = controls.filter(c => c.status === 'fail' && c.severity === 'critical').length

  // Intro paragraph
  doc.fillColor(COLORS.muted).font('Helvetica').fontSize(10).moveDown(0.5)
    .text(
      `This report presents the ${FRAMEWORK_LABELS[framework] || framework} compliance evidence collected for ${org.name} as of ${generatedAt.toLocaleDateString()}. Evidence was gathered automatically by the iFu Labs Comply platform via read-only access to your cloud infrastructure.`,
      { lineGap: 4 }
    )

  doc.moveDown(1)

  // Score summary table
  const tableX = 60
  const colW = (doc.page.width - 120) / 4
  const tableY = doc.y

  const cols = [
    { label: 'Passing',  value: passing,  color: COLORS.pass },
    { label: 'Failing',  value: failing,  color: COLORS.fail },
    { label: 'Review',   value: review,   color: COLORS.warn },
    { label: 'Pending',  value: pending,  color: COLORS.muted },
  ]

  cols.forEach((col, i) => {
    const x = tableX + i * colW
    doc.rect(x, tableY, colW - 8, 64).fill(COLORS.bg)
    doc.fillColor(col.color).font('Helvetica-Bold').fontSize(28)
      .text(String(col.value), x + 8, tableY + 8, { width: colW - 24, align: 'center' })
    doc.fillColor(COLORS.muted).font('Helvetica').fontSize(9)
      .text(col.label.toUpperCase(), x + 8, tableY + 44, { width: colW - 24, align: 'center' })
  })

  doc.moveDown(4.5)

  if (critical > 0) {
    doc.rect(60, doc.y, doc.page.width - 120, 32).fill('#FEF0EE')
    doc.fillColor(COLORS.fail).font('Helvetica-Bold').fontSize(10)
      .text(`⚠  ${critical} critical control${critical > 1 ? 's' : ''} require immediate attention.`, 68, doc.y + 10)
    doc.moveDown(2.2)
  }

  // Overall score bar
  doc.fillColor(COLORS.ink).font('Helvetica-Bold').fontSize(11)
    .text('Overall Compliance Score', { lineGap: 6 })

  const barW = doc.page.width - 120
  const barH = 12
  const barY = doc.y

  doc.rect(60, barY, barW, barH).fill(COLORS.border)
  const fillW = Math.round((score / 100) * barW)
  const barColor = score >= 80 ? COLORS.pass : score >= 60 ? COLORS.warn : COLORS.fail
  doc.rect(60, barY, fillW, barH).fill(barColor)

  doc.fillColor(COLORS.ink).font('Helvetica-Bold').fontSize(11)
    .text(`${score}%`, 60 + barW + 8, barY - 1)

  doc.moveDown(2)

  // Key findings
  doc.fillColor(COLORS.ink).font('Helvetica-Bold').fontSize(11).text('Key Findings').moveDown(0.5)

  const findings = []
  if (passing === total) findings.push({ text: `All ${total} controls are passing. Great work.`, positive: true })
  if (critical > 0)      findings.push({ text: `${critical} critical control(s) are failing and must be remediated before audit.`, positive: false })
  if (failing > 0 && critical === 0) findings.push({ text: `${failing} control(s) are failing and require attention.`, positive: false })
  if (pending > 0)       findings.push({ text: `${pending} control(s) have not been scanned yet. Connect additional integrations to automate these checks.`, positive: null })
  if (review > 0)        findings.push({ text: `${review} control(s) need manual review and evidence collection.`, positive: null })
  if (scans.length > 0)  findings.push({ text: `Last automated scan: ${new Date(scans[0].completedAt).toLocaleString()}. Scans run daily.`, positive: true })

  for (const finding of findings) {
    const bullet = finding.positive === true ? '✓' : finding.positive === false ? '✗' : '○'
    const color  = finding.positive === true ? COLORS.pass : finding.positive === false ? COLORS.fail : COLORS.muted
    doc.fillColor(color).font('Helvetica-Bold').fontSize(10).text(bullet, 60, doc.y, { continued: true })
    doc.fillColor(COLORS.ink).font('Helvetica').text(`  ${finding.text}`, { lineGap: 3 }).moveDown(0.4)
  }
}

function controlSection(doc, category, controls) {
  sectionHeader(doc, category)

  for (const control of controls) {
    if (doc.y > doc.page.height - 160) doc.addPage()

    const status = control.status || 'pending'
    const statusColor = { pass: COLORS.pass, fail: COLORS.fail, review: COLORS.warn, pending: COLORS.muted }[status] || COLORS.muted
    const statusLabel = { pass: 'PASS', fail: 'FAIL', review: 'REVIEW', pending: 'PENDING' }[status] || 'PENDING'

    const rowY = doc.y

    // Control ID + badge
    doc.fillColor(COLORS.muted).font('Helvetica').fontSize(8)
      .text(control.controlId, 60, rowY)

    // Status pill (right aligned)
    const pillW = 48
    const pillX = doc.page.width - 60 - pillW
    doc.rect(pillX, rowY - 2, pillW, 14).fill(statusColor + '22')
    doc.fillColor(statusColor).font('Helvetica-Bold').fontSize(7)
      .text(statusLabel, pillX, rowY + 1, { width: pillW, align: 'center' })

    // Title
    doc.fillColor(COLORS.ink).font('Helvetica-Bold').fontSize(10)
      .text(control.title, 60, rowY + 14, { width: doc.page.width - 140 })

    // Description
    doc.fillColor(COLORS.muted).font('Helvetica').fontSize(9)
      .text(control.description, 60, doc.y + 3, { width: doc.page.width - 120, lineGap: 2 })

    // Evidence detail (if available)
    if (control.evidence?.detail) {
      doc.moveDown(0.4)
      doc.rect(60, doc.y, doc.page.width - 120, 1).fill(COLORS.border)
      doc.moveDown(0.3)
      doc.fillColor(COLORS.muted).font('Helvetica-Oblique').fontSize(8.5)
        .text(`Evidence: ${control.evidence.detail}`, 60, doc.y, { width: doc.page.width - 120, lineGap: 2 })
    }

    // Guidance for failing controls
    if (status === 'fail' && control.guidance) {
      doc.moveDown(0.4)
      doc.rect(60, doc.y, 3, 0).fill(COLORS.fail)  // left accent bar
      doc.fillColor(COLORS.fail).font('Helvetica-Bold').fontSize(8)
        .text('Remediation: ', 68, doc.y, { continued: true })
      doc.fillColor(COLORS.ink).font('Helvetica').fontSize(8)
        .text(control.guidance.slice(0, 200) + (control.guidance.length > 200 ? '...' : ''), { width: doc.page.width - 128, lineGap: 2 })
    }

    // Notes
    if (control.notes) {
      doc.moveDown(0.3)
      doc.fillColor(COLORS.muted).font('Helvetica-Oblique').fontSize(8)
        .text(`Notes: ${control.notes}`, 60, doc.y, { width: doc.page.width - 120 })
    }

    // Checked at
    if (control.checkedAt) {
      doc.fillColor(COLORS.border).font('Helvetica').fontSize(7.5)
        .text(`Checked: ${new Date(control.checkedAt).toLocaleString()}`, 60, doc.y + 4)
    }

    // Divider
    doc.moveDown(0.8)
    doc.rect(60, doc.y, doc.page.width - 120, 0.5).fill(COLORS.border)
    doc.moveDown(0.6)
  }
}

function scanHistory(doc, scans) {
  sectionHeader(doc, 'Scan History')

  doc.fillColor(COLORS.muted).font('Helvetica').fontSize(10)
    .text('The following automated scans were performed against your infrastructure:', { lineGap: 4 })
  doc.moveDown(0.8)

  // Table header
  const cols = { date: 60, type: 180, pass: 300, fail: 360, total: 420, status: 470 }
  const headerY = doc.y

  doc.rect(60, headerY - 4, doc.page.width - 120, 20).fill(COLORS.bg)

  doc.fillColor(COLORS.muted).font('Helvetica-Bold').fontSize(8)
  doc.text('DATE', cols.date, headerY)
  doc.text('INTEGRATION', cols.type, headerY)
  doc.text('PASSED', cols.pass, headerY)
  doc.text('FAILED', cols.fail, headerY)
  doc.text('TOTAL', cols.total, headerY)
  doc.text('TRIGGER', cols.status, headerY)

  doc.moveDown(1.4)

  for (const scan of scans) {
    const y = doc.y
    doc.fillColor(COLORS.ink).font('Helvetica').fontSize(9)
    doc.text(new Date(scan.completedAt || scan.createdAt).toLocaleDateString(), cols.date, y)
    doc.text((scan.integrationType || 'aws').toUpperCase(), cols.type, y)
    doc.fillColor(COLORS.pass).text(String(scan.passCount || 0), cols.pass, y)
    doc.fillColor(scan.failCount > 0 ? COLORS.fail : COLORS.muted).text(String(scan.failCount || 0), cols.fail, y)
    doc.fillColor(COLORS.ink).text(String(scan.totalControls || 0), cols.total, y)
    doc.fillColor(COLORS.muted).text(scan.triggeredBy || 'schedule', cols.status, y)

    doc.moveDown(0.6)
    doc.rect(60, doc.y, doc.page.width - 120, 0.5).fill(COLORS.border)
    doc.moveDown(0.4)
  }
}

// ── Helpers ────────────────────────────────────────────────────────────────

function sectionHeader(doc, title) {
  doc.rect(60, doc.y, doc.page.width - 120, 2).fill(COLORS.accent)
  doc.moveDown(0.6)
  doc.fillColor(COLORS.accent).font('Helvetica-Bold').fontSize(16)
    .text(title)
  doc.moveDown(0.8)
}

function pageFooter(doc, pageNum, totalPages, orgName) {
  const y = doc.page.height - 40
  const w = doc.page.width

  doc.rect(60, y - 8, w - 120, 0.5).fill(COLORS.border)

  doc.fillColor(COLORS.muted).font('Helvetica').fontSize(8)
    .text('iFu Labs Comply — Compliance Automation', 60, y)
    .text(orgName, 60, y, { width: w - 120, align: 'center' })
    .text(`Page ${pageNum} of ${totalPages}`, 60, y, { width: w - 120, align: 'right' })
}
